### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by jiangjianping** [zijingcloud/Web-SDK#1]
1、转发端自定义layout：在WebRTC呼叫
clayout：多流端在会议室layout的基础上，希望接收到的流的数量和大小。格式为M:N，其中M为希望接受到的大视频流的数量，N为小流的数量，M+N不能超过会议室定义的layout对应的可能的最多“演员”人数。一般应用场景：
a. 1:N，可用于根据端的解码能力，限制端能够处理的视频数量为1个大流，N个小流
b. N:0，希望接受N个大流。如果N大于4， 则会议室的分频必须是1+7，1+21， 2+21。这里会有个限制：如果一个会议跨了多个节点，与该端不在同一个节点的参会者视频有可能是压缩编码过的，即视频质量会受影响
c. 不设置：遵循会议室的布局
2、参照“静音”新增“静画”功能
在参会者控制中增加
a. hard_vmute: 由主持人“静画”该参会者
b. hard_uvmute: 由主持人取消“静画”
c. soft_vmute: 由本人关闭本地摄像头时调用，告知平台侧本地画面已自行关闭
d. soft_uvmute: 在打开摄像头时调用，告知平台侧本地画面已打开
在参会者属性中，增加了两个相关属性：
a. is_vmute，同is_mute，表示是否被“静画”了。被静画的端可以考虑关闭摄像头，节省上传流量
b. v_muted    用于表示“静画”的原因。v_muted & 1 == 1： 表示是自身关闭了摄像头，即调用过soft_vmute；v_muted & 2 == 2：表示被主持人“静画”了。hard_vmute会覆盖soft_vmute，即在soft_vmute后调用了hard_vmute，原来的soft_vmute设置的标志会失效

**Comment by starcwl** [comment]
全平台已改好。  根据讨论结果， soft_vmute, soft_uvmute 暂时不添加。
