### ISSUE TITLE
通过API发送 start_service指令，响应{"status": "failed", "result": "['HEAD']"}这个失败，请看看是什么原因

### ISSUE THREAD

**Issue by GavinPong** [zijingcloud/Web-SDK#17]
* 操作系统及版本：
* 浏览器及版本：
* SDK版本：
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by starcwl** [comment]
能否提交一下你发的内容？ 最好能提供完整的http请求

**Comment by starcwl** [comment]
@GavinPong   问题是否解决？ 请尽快提交一下相关信息。

**Comment by GavinPong** [comment]
GET /api/services/1061/start_service HTTP/1.1
HOST:mcu.myvmr.cn
Cache-Control:no-cache
Referer:https://mcu.myvmr.cn/
role:
token:KW8vd819IslH4pwPI7mc52mK8QAEbVQFrlXrkImmzpcFb%2BIdp98KNjR8YnBAEOCD8LGoR7T/a3jp6GBDvaYJ%2BlqlU9HLO5rkQkQmvI3HpY1K/6bTfaT5AsoXKSRjst3zyhutIKwNCvnJ3Kij595zpwyJKOtZU9N0ynmobbPT6/xWEeeggEfRcNOz7yIli5YJrQ3xG8SWu57WhIJXNH7A0Q%3D%3D
pin:
Connection:keep-alive

**Comment by GavinPong** [comment]
问题已经解决，谢谢！
