### ISSUE TITLE
在发CheckJoin请求时，如果{"joinAccount":"1061", "participantName":"阿里"}中的participantName为中文时，会报错

### ISSUE THREAD

**Issue by GavinPong** [zijingcloud/Web-SDK#18]
* 操作系统及版本：
* 浏览器及版本：
* SDK版本：
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by GavinPong** [comment]
发送的内容：
POST /api/v3/meet/checkJoin.shtml HTTP/1.1
HOST:cs.zijingcloud.com
Cache-Control:no-cache
Origin:https://cs.zijingcloud.com/
Referer:https://cs.zijingcloud.com/
Content-Type:application/json;charset="utf-8"
Connection:keep-alive
role:
token:
pin:
Content-Length:48

{"joinAccount":"1061", "participantName":"阿里"}


接收的内容：
<html><head><title>Apache Tomcat/7.0.65 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.65</h3></body></html>

**Comment by starcwl** [comment]
@GavinPong 在chrome下测试没有问题，接口支持中文，请问服务器报什么错误？您的测试方法？

**Comment by GavinPong** [comment]
@starcwl 
1、我用的cs.zijingcloud.com服务器；
2、我用的c语言版openssl测试的；

**Comment by starcwl** [comment]
无法复现问题
根据提示“The request sent by the client was syntactically incorrect”. 可能是你的网络请求报文有问题。请测试一下您是否能正常POST json格式请求。
以下是我curl的请求结果：

`curl -H "Content-Type: application/json;charset="utf-8"" --request POST --data '{"joinAccount":"1061", "participantName":"阿里"}' https://cs.zijingcloud.com/api/v3/meet/checkJoin.shtml `

`{"code":"200","timeStamp":"2018-05-10 16:00:18","results":{"isDot":false,"sipkey":"1061","alias":"zjvmr@myvmr.cn","password":"","participantName":"阿里","roleType":"host","mcuHost":"mcu.myvmr.cn","companyId":52,"isRecord":true,"isLive":true,"conferenceName":"紫荆云视会议室1","allowGuest":"yes"}}`

**Comment by starcwl** [comment]
@GavinPong   如果没有新的回复，该issue在3天后关闭.
