### ISSUE TITLE
错误: 屏幕共享扩展未找到

### ISSUE THREAD

**Issue by harryxlb** [zijingcloud/Web-SDK#19]
* 操作系统及版本：Windows 7
* 浏览器及版本：Chrome/66.0.3359.139
* SDK版本：1.0
* 屏幕共享扩展：chrome.crx

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [x] 这是一个 **文档使用问题** 

### Code
　根据demo中提供的代码，修改入会方式为screen:
   `$scope.enterConference = function(){`
    `    rtc.makeCall(mcuHost, alias, displayName, null, 'screen');`
    `}`

### 运行代码后复现问题。

错误: 屏幕共享扩展未找到.
你是否想安装屏幕共享扩展?

### 代码期望的行为
共享屏幕成功
### 代码实际的行为
共享屏幕失败出错

**Comment by starcwl** [comment]
@harryxlb 已经增加屏幕共享demo，请测试
