### ISSUE TITLE
网页上在线列表不为空时，发送"/api/services/1061/participants"指令时，概率性的出现响应数据中result数组为空的情况

### ISSUE THREAD

**Issue by GavinPong** [zijingcloud/Web-SDK#21]
* 操作系统及版本：
* 浏览器及版本：
* SDK版本：

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by starcwl** [comment]
请提供一下完整的http请求，另外请标注一下uuid和时间戳，方便我们在后台定位一下。

**Comment by starcwl** [comment]
提供 uuid 和 时间是为了去后台找到你出问题的请求，判断是否有异常 @GavinPong

**Comment by GavinPong** [comment]
我的http请求中没带时戳和uuid，你是想我知道我在什么时间发的请求信息，然后你去服务器的日志中才看这个时间段的内容，然后找到异常原因对吗？

**Comment by starcwl** [comment]
@GavinPong  对的，如果能提供的话。

**Comment by starcwl** [comment]
@GavinPong   无法复现，故关闭问题。
