### ISSUE TITLE
调用修改屏幕布局命令后报400错误

### ISSUE THREAD

**Issue by harryxlb** [zijingcloud/Web-SDK#22]
* 操作系统及版本：Windows 7
* 浏览器及版本：Chrome/66.0.3359.181
* SDK版本：1.0
* 文档版本：Javascript接口API1.4.2，Rest会中管理API文档2.1.5

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [x] 这是一个 **文档使用问题** 

### Code

equest URL: https://mcu.myvmr.cn/api/services/6283/override_layout
Request Method: POST
Status Code: 400 Bad Request
Request payload:
{"layouts": [{
                    "audience": "hosts",
                    "actors": ["c99fbd36-3f97-4b14-b3c9-f5c8baa7cab5"],
                    "vad_backfill": true,
                    "layout": "1:7",
                    "plus_n": "auto",
                    "actors_overlay_text": "auto"
                },{
                    "audience": "",
                    "actors": ["c99fbd36-3f97-4b14-b3c9-f5c8baa7cab5"],
                    "vad_backfill": true,
                    "layout": "1:7",
                    "plus_n": "auto",
                    "actors_overlay_text": "auto"
                }]
            }

### 运行代码后复现问题。
Error: 
    POST https://mcu.myvmr.cn/api/services/6283/override_layout 400 (Bad Request)
### 代码期望的行为
执行成功，屏幕布局1:7，且主屏幕上显示指定参会人，当指定多个actors时按顺序排列
### 代码实际的行为
执行出错

**Comment by starcwl** [comment]
根据Override_layout命令文档提示：     “off”:actors不为空时;”auto”:其它情况
@harryxlb
