### ISSUE TITLE
同一参会人出现多个重复画面

### ISSUE THREAD

**Issue by harryxlb** [zijingcloud/Web-SDK#23]
* 操作系统及版本：Windows 7
* 浏览器及版本：Chrome/67.0.3396.99
* SDK版本：1.0

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

复现步骤：
webrtc客户端入会以后，刷新几次页面，有一定几率出现重复画面问题，在紫荆云会议室也可以看到。

### 代码期望的行为
同一客户端唯一画面
### 代码实际的行为
同一客户端多个画面

**Comment by starcwl** [comment]
刷新页面导致了非正常退会， 后端判断与会者退会考虑到网络变化需要一定时间。所以这个问题不是bug。
