### ISSUE TITLE
参会人视频方式入会不能接收流

### ISSUE THREAD

**Issue by harryxlb** [zijingcloud/Web-SDK#24]
参会以视频方式入会不能接收流

* 操作系统及版本：windows 7
* 浏览器及版本：Firefox 59、Firefox 61
* SDK版本：1.0

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [x] 这是一个 **文档使用问题** 

### Code
`var apiServer = 'cs.zijingcloud.com',
      mcuHost = '',
      // alias = '1061',
      alias = '6283',
      password = '',
      displayName = 'demo';
    // rtc.pin = password;

    var data = {
        joinAccount: alias,
        joinPwd:password,
        participantName:displayName
    }

    // get conference information
    Meet.getAuth(apiServer, data).$promise.then(function(res){
      if(res.code === '200')
      {
        mcuHost = res.results.mcuHost; rtc.pin = password
        zjReg.register(mcuHost, 'feng.wang@zijingcloud.com', 'wang@2015');
      }
      else
        alert(res.results);
    })
    .catch(function(err){
      alert(`接口异常，请确认您有权访问该接口:${err.config.url}。`);
    })

    // click enter to conference
    $scope.enterConference = function(){
        rtc.makeCall(mcuHost, alias, displayName, null, 'video');
    }`

### 运行代码后复现问题。
1>多个参会人以'video'方式入会
2>另一参会人以'recvonly'方式入会，以'recvonly'方式入会的参会人可以看到以'video'方式入会的参会人，以'video'方式入会的参会人看不到任何人，画面黑色
### 代码期望的行为
以'video'方式入会的参会人可以看到其它'video'方式入会的参会人
### 代码实际的行为
以'video'方式入会的参会人看不到任何人，画面黑色

**Comment by starcwl** [comment]
无法复现问题

**Comment by starcwl** [comment]
无法复现问题

**Comment by starcwl** [comment]
建议用最新的demo代码测试。 如果仍然复现，请把您的代码放在公网上，并给出访问链接，我这边链进去看看。
