### ISSUE TITLE
IOS、Android、浏览器等在关闭时应发送退会请求

### ISSUE THREAD

**Issue by jiangjianping** [zijingcloud/Web-SDK#5]
在关闭浏览器、IOS、Android APP时，应发送disconnect 请求退会，而否现在的超时后与会者被动退出。

**Comment by starcwl** [comment]
web端功能已经存在。 iOS ,Android已经建立相应issue

**Comment by starcwl** [comment]
var _oldUnload = window.onbeforeunload;
        window.onbeforeunload = function () {
            $.get( "http://192.168.2.1:9911/onbeforeunload", function( data ) {});
        }
        window.onunload = function(){
            $.get( "http://192.168.2.1:9911/onunload", function( data ) {});
        }
        window.unload = function(){
            $.get( "http://192.168.2.1:9911/unload", function( data ) {});
        }

        window.addEventListener('pageshow', function(){
            console.log('pageshow');
        });
        window.addEventListener('pagehide', function(){
            $.get( "http://192.168.2.1:9911/hide", function( data ) {});
            console.log('pagehide');
        });

        window.onpageshow = function(){
            $.get( "http://192.168.2.1:9911/show", function( data ) {});
        }

        var _oldPh = window.onpagehide;
        window.onpagehide = function(){
            $.get( "http://192.168.2.1:9911/hide2", function( data ) {});
        }

        $(window).on('pageshow', function(e) {
            $.get( "http://192.168.2.1:9911/pageshow", function( data ) {});
        })
        $(window).on('pagehide', function(e) {
            $.get( "http://192.168.2.1:9911/pagehide", function( data ) {});
        })

以上事件，关闭tag时，不能保证每次都运行， 另外关闭safari时不运行。
